// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	message "github.com/gagarinchain/common/message"
	mock "github.com/stretchr/testify/mock"
)

// Dispatcher is an autogenerated mock type for the Dispatcher type
type Dispatcher struct {
	mock.Mock
}

// Dispatch provides a mock function with given fields: msg
func (_m *Dispatcher) Dispatch(msg *message.Message) {
	_m.Called(msg)
}
