// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/gagarinchain/common"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// EventBus is an autogenerated mock type for the EventBus type
type EventBus struct {
	mock.Mock
}

// FireEvent provides a mock function with given fields: event
func (_m *EventBus) FireEvent(event *common.Event) {
	_m.Called(event)
}

// Run provides a mock function with given fields: ctx
func (_m *EventBus) Run(ctx context.Context) {
	_m.Called(ctx)
}

// Subscribe provides a mock function with given fields: id, writer
func (_m *EventBus) Subscribe(id string, writer io.Writer) {
	_m.Called(id, writer)
}

// Unsubscribe provides a mock function with given fields: id
func (_m *EventBus) Unsubscribe(id string) {
	_m.Called(id)
}
