// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EventPayload is an autogenerated mock type for the EventPayload type
type EventPayload struct {
	mock.Mock
}
