// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	pb "github.com/gagarinchain/common/protobuff"
)

// OnBlockCommitClient is an autogenerated mock type for the OnBlockCommitClient type
type OnBlockCommitClient struct {
	mock.Mock
}

// OnBlockCommit provides a mock function with given fields: ctx, in, opts
func (_m *OnBlockCommitClient) OnBlockCommit(ctx context.Context, in *pb.OnBlockCommitRequest, opts ...grpc.CallOption) (*pb.OnBlockCommitResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *pb.OnBlockCommitResponse
	if rf, ok := ret.Get(0).(func(context.Context, *pb.OnBlockCommitRequest, ...grpc.CallOption) *pb.OnBlockCommitResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.OnBlockCommitResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.OnBlockCommitRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
