// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// OnNextView is an autogenerated mock type for the OnNextView type
type OnNextView struct {
	mock.Mock
}

// OnNewView provides a mock function with given fields: ctx, newView
func (_m *OnNextView) OnNewView(ctx context.Context, newView int32) error {
	ret := _m.Called(ctx, newView)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, newView)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
