// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	api "github.com/gagarinchain/common/api"
	mock "github.com/stretchr/testify/mock"
)

// OnNextEpoch is an autogenerated mock type for the OnNextEpoch type
type OnNextEpoch struct {
	mock.Mock
}

// OnNewEpoch provides a mock function with given fields: pacer, bc, newEpoch
func (_m *OnNextEpoch) OnNewEpoch(pacer api.Pacer, bc api.Blockchain, newEpoch int32) error {
	ret := _m.Called(pacer, bc, newEpoch)

	var r0 error
	if rf, ok := ret.Get(0).(func(api.Pacer, api.Blockchain, int32) error); ok {
		r0 = rf(pacer, bc, newEpoch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
