// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	context "context"

	pb "github.com/gagarinchain/common/protobuff"
	mock "github.com/stretchr/testify/mock"
)

// OnNewBlockCreatedServer is an autogenerated mock type for the OnNewBlockCreatedServer type
type OnNewBlockCreatedServer struct {
	mock.Mock
}

// OnNewBlockCreated provides a mock function with given fields: _a0, _a1
func (_m *OnNewBlockCreatedServer) OnNewBlockCreated(_a0 context.Context, _a1 *pb.OnNewBlockCreatedRequest) (*pb.OnNewBlockCreatedResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pb.OnNewBlockCreatedResponse
	if rf, ok := ret.Get(0).(func(context.Context, *pb.OnNewBlockCreatedRequest) *pb.OnNewBlockCreatedResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.OnNewBlockCreatedResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.OnNewBlockCreatedRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
