// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	api "github.com/gagarinchain/common/api"
	mock "github.com/stretchr/testify/mock"
)

// OnNextView is an autogenerated mock type for the OnNextView type
type OnNextView struct {
	mock.Mock
}

// OnNewView provides a mock function with given fields: pacer, bc, newView
func (_m *OnNextView) OnNewView(pacer api.Pacer, bc api.Blockchain, newView int32) error {
	ret := _m.Called(pacer, bc, newView)

	var r0 error
	if rf, ok := ret.Get(0).(func(api.Pacer, api.Blockchain, int32) error); ok {
		r0 = rf(pacer, bc, newView)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
