// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/gagarinchain/common/api"

	mock "github.com/stretchr/testify/mock"
)

// OnNewBlockCreated is an autogenerated mock type for the OnNewBlockCreated type
type OnNewBlockCreated struct {
	mock.Mock
}

// OnNewBlockCreated provides a mock function with given fields: ctx, builder, receipts
func (_m *OnNewBlockCreated) OnNewBlockCreated(ctx context.Context, builder api.BlockBuilder, receipts []api.Receipt) (api.Block, error) {
	ret := _m.Called(ctx, builder, receipts)

	var r0 api.Block
	if rf, ok := ret.Get(0).(func(context.Context, api.BlockBuilder, []api.Receipt) api.Block); ok {
		r0 = rf(ctx, builder, receipts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.Block)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, api.BlockBuilder, []api.Receipt) error); ok {
		r1 = rf(ctx, builder, receipts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
