// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/gagarinchain/common/api"

	mock "github.com/stretchr/testify/mock"
)

// OnReceiveProposal is an autogenerated mock type for the OnReceiveProposal type
type OnReceiveProposal struct {
	mock.Mock
}

// AfterProposedBlockAdded provides a mock function with given fields: ctx, proposal, receipts
func (_m *OnReceiveProposal) AfterProposedBlockAdded(ctx context.Context, proposal api.Proposal, receipts []api.Receipt) error {
	ret := _m.Called(ctx, proposal, receipts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, api.Proposal, []api.Receipt) error); ok {
		r0 = rf(ctx, proposal, receipts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AfterVoted provides a mock function with given fields: ctx, vote
func (_m *OnReceiveProposal) AfterVoted(ctx context.Context, vote api.Vote) error {
	ret := _m.Called(ctx, vote)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, api.Vote) error); ok {
		r0 = rf(ctx, vote)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BeforeProposedBlockAdded provides a mock function with given fields: ctx, proposal
func (_m *OnReceiveProposal) BeforeProposedBlockAdded(ctx context.Context, proposal api.Proposal) error {
	ret := _m.Called(ctx, proposal)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, api.Proposal) error); ok {
		r0 = rf(ctx, proposal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BeforeVoted provides a mock function with given fields: ctx, vote
func (_m *OnReceiveProposal) BeforeVoted(ctx context.Context, vote api.Vote) error {
	ret := _m.Called(ctx, vote)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, api.Vote) error); ok {
		r0 = rf(ctx, vote)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
