// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	context "context"

	pb "github.com/gagarinchain/common/protobuff"
	mock "github.com/stretchr/testify/mock"
)

// OnVoteReceivedServer is an autogenerated mock type for the OnVoteReceivedServer type
type OnVoteReceivedServer struct {
	mock.Mock
}

// OnQCFinished provides a mock function with given fields: _a0, _a1
func (_m *OnVoteReceivedServer) OnQCFinished(_a0 context.Context, _a1 *pb.OnQCFinishedRequest) (*pb.OnQCFinishedResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pb.OnQCFinishedResponse
	if rf, ok := ret.Get(0).(func(context.Context, *pb.OnQCFinishedRequest) *pb.OnQCFinishedResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.OnQCFinishedResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.OnQCFinishedRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OnVoteReceived provides a mock function with given fields: _a0, _a1
func (_m *OnVoteReceivedServer) OnVoteReceived(_a0 context.Context, _a1 *pb.OnVoteReceivedRequest) (*pb.OnVoteReceivedResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pb.OnVoteReceivedResponse
	if rf, ok := ret.Get(0).(func(context.Context, *pb.OnVoteReceivedRequest) *pb.OnVoteReceivedResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.OnVoteReceivedResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.OnVoteReceivedRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
