// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	api "github.com/gagarinchain/common/api"
	mock "github.com/stretchr/testify/mock"
)

// OnVoteReceived is an autogenerated mock type for the OnVoteReceived type
type OnVoteReceived struct {
	mock.Mock
}

// OnQCFinished provides a mock function with given fields: pacer, bc, qc
func (_m *OnVoteReceived) OnQCFinished(pacer api.Pacer, bc api.Blockchain, qc api.QuorumCertificate) error {
	ret := _m.Called(pacer, bc, qc)

	var r0 error
	if rf, ok := ret.Get(0).(func(api.Pacer, api.Blockchain, api.QuorumCertificate) error); ok {
		r0 = rf(pacer, bc, qc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnVoteReceived provides a mock function with given fields: pacer, bc, vote
func (_m *OnVoteReceived) OnVoteReceived(pacer api.Pacer, bc api.Blockchain, vote api.Vote) error {
	ret := _m.Called(pacer, bc, vote)

	var r0 error
	if rf, ok := ret.Get(0).(func(api.Pacer, api.Blockchain, api.Vote) error); ok {
		r0 = rf(pacer, bc, vote)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
