// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/gagarinchain/common/api"

	mock "github.com/stretchr/testify/mock"
)

// OnVoteReceived is an autogenerated mock type for the OnVoteReceived type
type OnVoteReceived struct {
	mock.Mock
}

// OnQCFinished provides a mock function with given fields: ctx, qc
func (_m *OnVoteReceived) OnQCFinished(ctx context.Context, qc api.QuorumCertificate) error {
	ret := _m.Called(ctx, qc)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, api.QuorumCertificate) error); ok {
		r0 = rf(ctx, qc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnVoteReceived provides a mock function with given fields: ctx, vote
func (_m *OnVoteReceived) OnVoteReceived(ctx context.Context, vote api.Vote) error {
	ret := _m.Called(ctx, vote)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, api.Vote) error); ok {
		r0 = rf(ctx, vote)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
