// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	big "math/big"

	api "github.com/gagarinchain/common/api"

	common "github.com/gagarinchain/common/eth/common"

	crypto "github.com/gagarinchain/common/eth/crypto"

	gagarinchaincommon "github.com/gagarinchain/common"

	mock "github.com/stretchr/testify/mock"
)

// Pacer is an autogenerated mock type for the Pacer type
type Pacer struct {
	mock.Mock
}

// FireEvent provides a mock function with given fields: event
func (_m *Pacer) FireEvent(event api.Event) {
	_m.Called(event)
}

// GetBitmap provides a mock function with given fields: src
func (_m *Pacer) GetBitmap(src map[common.Address]*crypto.Signature) *big.Int {
	ret := _m.Called(src)

	var r0 *big.Int
	if rf, ok := ret.Get(0).(func(map[common.Address]*crypto.Signature) *big.Int); ok {
		r0 = rf(src)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	return r0
}

// GetCurrent provides a mock function with given fields:
func (_m *Pacer) GetCurrent() *gagarinchaincommon.Peer {
	ret := _m.Called()

	var r0 *gagarinchaincommon.Peer
	if rf, ok := ret.Get(0).(func() *gagarinchaincommon.Peer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gagarinchaincommon.Peer)
		}
	}

	return r0
}

// GetCurrentEpoch provides a mock function with given fields:
func (_m *Pacer) GetCurrentEpoch() int32 {
	ret := _m.Called()

	var r0 int32
	if rf, ok := ret.Get(0).(func() int32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int32)
	}

	return r0
}

// GetCurrentView provides a mock function with given fields:
func (_m *Pacer) GetCurrentView() int32 {
	ret := _m.Called()

	var r0 int32
	if rf, ok := ret.Get(0).(func() int32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int32)
	}

	return r0
}

// GetNext provides a mock function with given fields:
func (_m *Pacer) GetNext() *gagarinchaincommon.Peer {
	ret := _m.Called()

	var r0 *gagarinchaincommon.Peer
	if rf, ok := ret.Get(0).(func() *gagarinchaincommon.Peer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gagarinchaincommon.Peer)
		}
	}

	return r0
}

// GetPeers provides a mock function with given fields:
func (_m *Pacer) GetPeers() []*gagarinchaincommon.Peer {
	ret := _m.Called()

	var r0 []*gagarinchaincommon.Peer
	if rf, ok := ret.Get(0).(func() []*gagarinchaincommon.Peer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gagarinchaincommon.Peer)
		}
	}

	return r0
}

// NotifyEvent provides a mock function with given fields: event
func (_m *Pacer) NotifyEvent(event api.Event) {
	_m.Called(event)
}

// ProposerForHeight provides a mock function with given fields: blockHeight
func (_m *Pacer) ProposerForHeight(blockHeight int32) *gagarinchaincommon.Peer {
	ret := _m.Called(blockHeight)

	var r0 *gagarinchaincommon.Peer
	if rf, ok := ret.Get(0).(func(int32) *gagarinchaincommon.Peer); ok {
		r0 = rf(blockHeight)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gagarinchaincommon.Peer)
		}
	}

	return r0
}

// SubscribeProtocolEvents provides a mock function with given fields: sub
func (_m *Pacer) SubscribeProtocolEvents(sub chan api.Event) {
	_m.Called(sub)
}
