// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
)

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// ReadMsg provides a mock function with given fields: msg
func (_m *Reader) ReadMsg(msg protoiface.MessageV1) error {
	ret := _m.Called(msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(protoiface.MessageV1) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
