// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
)

// ReadCloser is an autogenerated mock type for the ReadCloser type
type ReadCloser struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *ReadCloser) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadMsg provides a mock function with given fields: msg
func (_m *ReadCloser) ReadMsg(msg protoiface.MessageV1) error {
	ret := _m.Called(msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(protoiface.MessageV1) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
