// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
)

// Writer is an autogenerated mock type for the Writer type
type Writer struct {
	mock.Mock
}

// WriteMsg provides a mock function with given fields: _a0
func (_m *Writer) WriteMsg(_a0 protoiface.MessageV1) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(protoiface.MessageV1) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
