// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event_EventType int32

const (
	Event_RESERVED      Event_EventType = 0
	Event_BLOCK_ADDED   Event_EventType = 1
	Event_EPOCH_STARTED Event_EventType = 2
	Event_VIEW_CHANGED  Event_EventType = 3
	Event_COMMITTED     Event_EventType = 4
	Event_ACCOUNT       Event_EventType = 5
	Event_BLOCK         Event_EventType = 6
)

var Event_EventType_name = map[int32]string{
	0: "RESERVED",
	1: "BLOCK_ADDED",
	2: "EPOCH_STARTED",
	3: "VIEW_CHANGED",
	4: "COMMITTED",
	5: "ACCOUNT",
	6: "BLOCK",
}

var Event_EventType_value = map[string]int32{
	"RESERVED":      0,
	"BLOCK_ADDED":   1,
	"EPOCH_STARTED": 2,
	"VIEW_CHANGED":  3,
	"COMMITTED":     4,
	"ACCOUNT":       5,
	"BLOCK":         6,
}

func (x Event_EventType) String() string {
	return proto.EnumName(Event_EventType_name, int32(x))
}

func (Event_EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0, 0}
}

type Request_RequestType int32

const (
	Request_ACCOUNT Request_RequestType = 0
	Request_BLOCK   Request_RequestType = 1
)

var Request_RequestType_name = map[int32]string{
	0: "ACCOUNT",
	1: "BLOCK",
}

var Request_RequestType_value = map[string]int32{
	"ACCOUNT": 0,
	"BLOCK":   1,
}

func (x Request_RequestType) String() string {
	return proto.EnumName(Request_RequestType_name, int32(x))
}

func (Request_RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1, 0}
}

type Event struct {
	Type                 Event_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=gagarin.network.event.Event_EventType" json:"type,omitempty"`
	Id                   []byte          `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Payload              *any.Any        `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() Event_EventType {
	if m != nil {
		return m.Type
	}
	return Event_RESERVED
}

func (m *Event) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Event) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Request struct {
	Type                 Request_RequestType `protobuf:"varint,1,opt,name=type,proto3,enum=gagarin.network.event.Request_RequestType" json:"type,omitempty"`
	Id                   []byte              `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Payload              *any.Any            `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetType() Request_RequestType {
	if m != nil {
		return m.Type
	}
	return Request_ACCOUNT
}

func (m *Request) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Request) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type EpochStartedPayload struct {
	Epoch                int32    `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EpochStartedPayload) Reset()         { *m = EpochStartedPayload{} }
func (m *EpochStartedPayload) String() string { return proto.CompactTextString(m) }
func (*EpochStartedPayload) ProtoMessage()    {}
func (*EpochStartedPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2}
}

func (m *EpochStartedPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpochStartedPayload.Unmarshal(m, b)
}
func (m *EpochStartedPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpochStartedPayload.Marshal(b, m, deterministic)
}
func (m *EpochStartedPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochStartedPayload.Merge(m, src)
}
func (m *EpochStartedPayload) XXX_Size() int {
	return xxx_messageInfo_EpochStartedPayload.Size(m)
}
func (m *EpochStartedPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochStartedPayload.DiscardUnknown(m)
}

var xxx_messageInfo_EpochStartedPayload proto.InternalMessageInfo

func (m *EpochStartedPayload) GetEpoch() int32 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

type ViewChangedPayload struct {
	View                 int32    `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewChangedPayload) Reset()         { *m = ViewChangedPayload{} }
func (m *ViewChangedPayload) String() string { return proto.CompactTextString(m) }
func (*ViewChangedPayload) ProtoMessage()    {}
func (*ViewChangedPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{3}
}

func (m *ViewChangedPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewChangedPayload.Unmarshal(m, b)
}
func (m *ViewChangedPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewChangedPayload.Marshal(b, m, deterministic)
}
func (m *ViewChangedPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewChangedPayload.Merge(m, src)
}
func (m *ViewChangedPayload) XXX_Size() int {
	return xxx_messageInfo_ViewChangedPayload.Size(m)
}
func (m *ViewChangedPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewChangedPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ViewChangedPayload proto.InternalMessageInfo

func (m *ViewChangedPayload) GetView() int32 {
	if m != nil {
		return m.View
	}
	return 0
}

type CommittedPayload struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommittedPayload) Reset()         { *m = CommittedPayload{} }
func (m *CommittedPayload) String() string { return proto.CompactTextString(m) }
func (*CommittedPayload) ProtoMessage()    {}
func (*CommittedPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{4}
}

func (m *CommittedPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommittedPayload.Unmarshal(m, b)
}
func (m *CommittedPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommittedPayload.Marshal(b, m, deterministic)
}
func (m *CommittedPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommittedPayload.Merge(m, src)
}
func (m *CommittedPayload) XXX_Size() int {
	return xxx_messageInfo_CommittedPayload.Size(m)
}
func (m *CommittedPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_CommittedPayload.DiscardUnknown(m)
}

var xxx_messageInfo_CommittedPayload proto.InternalMessageInfo

func (m *CommittedPayload) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type AccountRequestPayload struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Block                []byte   `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRequestPayload) Reset()         { *m = AccountRequestPayload{} }
func (m *AccountRequestPayload) String() string { return proto.CompactTextString(m) }
func (*AccountRequestPayload) ProtoMessage()    {}
func (*AccountRequestPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{5}
}

func (m *AccountRequestPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRequestPayload.Unmarshal(m, b)
}
func (m *AccountRequestPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRequestPayload.Marshal(b, m, deterministic)
}
func (m *AccountRequestPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRequestPayload.Merge(m, src)
}
func (m *AccountRequestPayload) XXX_Size() int {
	return xxx_messageInfo_AccountRequestPayload.Size(m)
}
func (m *AccountRequestPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRequestPayload.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRequestPayload proto.InternalMessageInfo

func (m *AccountRequestPayload) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *AccountRequestPayload) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

type AccountResponsePayload struct {
	Account              *AccountE `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AccountResponsePayload) Reset()         { *m = AccountResponsePayload{} }
func (m *AccountResponsePayload) String() string { return proto.CompactTextString(m) }
func (*AccountResponsePayload) ProtoMessage()    {}
func (*AccountResponsePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{6}
}

func (m *AccountResponsePayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountResponsePayload.Unmarshal(m, b)
}
func (m *AccountResponsePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountResponsePayload.Marshal(b, m, deterministic)
}
func (m *AccountResponsePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountResponsePayload.Merge(m, src)
}
func (m *AccountResponsePayload) XXX_Size() int {
	return xxx_messageInfo_AccountResponsePayload.Size(m)
}
func (m *AccountResponsePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountResponsePayload.DiscardUnknown(m)
}

var xxx_messageInfo_AccountResponsePayload proto.InternalMessageInfo

func (m *AccountResponsePayload) GetAccount() *AccountE {
	if m != nil {
		return m.Account
	}
	return nil
}

type AccountUpdatedPayload struct {
	Old                  *AccountE `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New                  *AccountE `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AccountUpdatedPayload) Reset()         { *m = AccountUpdatedPayload{} }
func (m *AccountUpdatedPayload) String() string { return proto.CompactTextString(m) }
func (*AccountUpdatedPayload) ProtoMessage()    {}
func (*AccountUpdatedPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{7}
}

func (m *AccountUpdatedPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountUpdatedPayload.Unmarshal(m, b)
}
func (m *AccountUpdatedPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountUpdatedPayload.Marshal(b, m, deterministic)
}
func (m *AccountUpdatedPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountUpdatedPayload.Merge(m, src)
}
func (m *AccountUpdatedPayload) XXX_Size() int {
	return xxx_messageInfo_AccountUpdatedPayload.Size(m)
}
func (m *AccountUpdatedPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountUpdatedPayload.DiscardUnknown(m)
}

var xxx_messageInfo_AccountUpdatedPayload proto.InternalMessageInfo

func (m *AccountUpdatedPayload) GetOld() *AccountE {
	if m != nil {
		return m.Old
	}
	return nil
}

func (m *AccountUpdatedPayload) GetNew() *AccountE {
	if m != nil {
		return m.New
	}
	return nil
}

type AccountE struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Block                []byte   `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	Nonce                uint64   `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Value                uint64   `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	Proof                [][]byte `protobuf:"bytes,5,rep,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountE) Reset()         { *m = AccountE{} }
func (m *AccountE) String() string { return proto.CompactTextString(m) }
func (*AccountE) ProtoMessage()    {}
func (*AccountE) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{8}
}

func (m *AccountE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountE.Unmarshal(m, b)
}
func (m *AccountE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountE.Marshal(b, m, deterministic)
}
func (m *AccountE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountE.Merge(m, src)
}
func (m *AccountE) XXX_Size() int {
	return xxx_messageInfo_AccountE.Size(m)
}
func (m *AccountE) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountE.DiscardUnknown(m)
}

var xxx_messageInfo_AccountE proto.InternalMessageInfo

func (m *AccountE) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *AccountE) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *AccountE) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *AccountE) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *AccountE) GetProof() [][]byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func init() {
	proto.RegisterEnum("gagarin.network.event.Event_EventType", Event_EventType_name, Event_EventType_value)
	proto.RegisterEnum("gagarin.network.event.Request_RequestType", Request_RequestType_name, Request_RequestType_value)
	proto.RegisterType((*Event)(nil), "gagarin.network.event.Event")
	proto.RegisterType((*Request)(nil), "gagarin.network.event.Request")
	proto.RegisterType((*EpochStartedPayload)(nil), "gagarin.network.event.EpochStartedPayload")
	proto.RegisterType((*ViewChangedPayload)(nil), "gagarin.network.event.ViewChangedPayload")
	proto.RegisterType((*CommittedPayload)(nil), "gagarin.network.event.CommittedPayload")
	proto.RegisterType((*AccountRequestPayload)(nil), "gagarin.network.event.AccountRequestPayload")
	proto.RegisterType((*AccountResponsePayload)(nil), "gagarin.network.event.AccountResponsePayload")
	proto.RegisterType((*AccountUpdatedPayload)(nil), "gagarin.network.event.AccountUpdatedPayload")
	proto.RegisterType((*AccountE)(nil), "gagarin.network.event.AccountE")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x41, 0x6b, 0xdb, 0x30,
	0x1c, 0xc5, 0xeb, 0xc4, 0x6e, 0xda, 0xbf, 0xd3, 0xce, 0xd3, 0xda, 0xe1, 0xed, 0xb2, 0x60, 0x58,
	0x09, 0x1b, 0xb8, 0x2c, 0x3b, 0x6d, 0x87, 0x81, 0x6b, 0x8b, 0xb6, 0x6c, 0x6d, 0x8a, 0x92, 0x66,
	0xb0, 0x4b, 0x50, 0x62, 0x35, 0x31, 0x4d, 0x25, 0xcf, 0x76, 0x12, 0x0c, 0xdb, 0x77, 0xda, 0xf7,
	0xdb, 0x65, 0x48, 0xb6, 0x93, 0x14, 0x56, 0xe8, 0x60, 0x97, 0x44, 0xff, 0xa7, 0xdf, 0x7b, 0x3c,
	0xc9, 0x02, 0x93, 0x2d, 0x18, 0xcf, 0xdc, 0x38, 0x11, 0x99, 0x40, 0x87, 0x13, 0x3a, 0xa1, 0x49,
	0xc4, 0x5d, 0xce, 0xb2, 0xa5, 0x48, 0x6e, 0x5d, 0xb5, 0xf9, 0xf2, 0xc5, 0x44, 0x88, 0xc9, 0x8c,
	0x1d, 0x2b, 0x68, 0x34, 0xbf, 0x39, 0xa6, 0x3c, 0x2f, 0x1c, 0xce, 0x6f, 0x0d, 0x0c, 0x2c, 0x21,
	0xf4, 0x11, 0xf4, 0x2c, 0x8f, 0x99, 0xad, 0xb5, 0xb4, 0xf6, 0x7e, 0xe7, 0xc8, 0xfd, 0x6b, 0x94,
	0x8b, 0xd7, 0xbf, 0xfd, 0x3c, 0x66, 0x44, 0x79, 0xd0, 0x3e, 0xd4, 0xa2, 0xd0, 0xae, 0xb5, 0xb4,
	0x76, 0x93, 0xd4, 0xa2, 0x10, 0xb9, 0xd0, 0x88, 0x69, 0x3e, 0x13, 0x34, 0xb4, 0xeb, 0x2d, 0xad,
	0x6d, 0x76, 0x0e, 0xdc, 0xa2, 0x82, 0x5b, 0x55, 0x70, 0x3d, 0x9e, 0x93, 0x0a, 0x72, 0x16, 0xb0,
	0xbb, 0x8a, 0x44, 0x4d, 0xd8, 0x21, 0xb8, 0x87, 0xc9, 0x00, 0x07, 0xd6, 0x16, 0x7a, 0x02, 0xe6,
	0xc9, 0x97, 0xae, 0xff, 0x79, 0xe8, 0x05, 0x01, 0x0e, 0x2c, 0x0d, 0x3d, 0x85, 0x3d, 0x7c, 0xd5,
	0xf5, 0xcf, 0x86, 0xbd, 0xbe, 0x47, 0xfa, 0x38, 0xb0, 0x6a, 0xc8, 0x82, 0xe6, 0xe0, 0x1c, 0x7f,
	0x1d, 0xfa, 0x67, 0xde, 0xe5, 0x29, 0x0e, 0xac, 0x3a, 0xda, 0x83, 0x5d, 0xbf, 0x7b, 0x71, 0x71,
	0xde, 0x97, 0x80, 0x8e, 0x4c, 0x68, 0x78, 0xbe, 0xdf, 0xbd, 0xbe, 0xec, 0x5b, 0x06, 0xda, 0x05,
	0x43, 0x25, 0x5a, 0xdb, 0xce, 0x2f, 0x0d, 0x1a, 0x84, 0x7d, 0x9f, 0xb3, 0x34, 0x43, 0x9f, 0xee,
	0x9d, 0xff, 0xcd, 0x03, 0xe7, 0x2f, 0xe9, 0xea, 0xff, 0x3f, 0xde, 0xc1, 0x6b, 0x30, 0x37, 0x42,
	0x37, 0x2b, 0x6f, 0xad, 0x2b, 0x6b, 0xce, 0x5b, 0x78, 0x86, 0x63, 0x31, 0x9e, 0xf6, 0x32, 0x9a,
	0x64, 0x2c, 0xbc, 0x2a, 0xdc, 0xe8, 0x00, 0x0c, 0x26, 0x65, 0x55, 0xdf, 0x20, 0xc5, 0xe0, 0xb4,
	0x01, 0x0d, 0x22, 0xb6, 0xf4, 0xa7, 0x94, 0x4f, 0xd6, 0x2c, 0x02, 0x7d, 0x11, 0xb1, 0x65, 0x89,
	0xaa, 0xb5, 0x73, 0x04, 0x96, 0x2f, 0xee, 0xee, 0xa2, 0x2c, 0xbb, 0xc7, 0x4d, 0x69, 0x5a, 0x44,
	0x36, 0x89, 0x5a, 0x3b, 0xa7, 0x70, 0xe8, 0x8d, 0xc7, 0x62, 0xce, 0xb3, 0xb2, 0x6c, 0x05, 0xdb,
	0xd0, 0xa0, 0x61, 0x98, 0xb0, 0x34, 0x2d, 0xf9, 0x6a, 0x94, 0xd5, 0x46, 0x33, 0x31, 0xbe, 0x2d,
	0xef, 0xa6, 0x18, 0x9c, 0x1e, 0x3c, 0x5f, 0x05, 0xa5, 0xb1, 0xe0, 0x29, 0xab, 0x92, 0x3e, 0x40,
	0x83, 0x16, 0x3b, 0x2a, 0xc9, 0xec, 0xbc, 0x7a, 0xe0, 0x5b, 0x94, 0x7e, 0x4c, 0x2a, 0xde, 0xf9,
	0xb9, 0x6a, 0x77, 0x1d, 0x87, 0x74, 0xe3, 0x28, 0xef, 0xa0, 0x2e, 0x66, 0xe1, 0x63, 0xf3, 0x24,
	0x2b, 0x2d, 0x9c, 0x2d, 0x55, 0xe9, 0xc7, 0x58, 0x38, 0x5b, 0x3a, 0x3f, 0x60, 0xa7, 0x12, 0xfe,
	0xf5, 0x3e, 0xa4, 0xca, 0x05, 0x1f, 0x33, 0xf5, 0x58, 0x74, 0x52, 0x0c, 0x52, 0x5d, 0xd0, 0xd9,
	0x9c, 0xd9, 0x7a, 0xa1, 0xaa, 0x41, 0xaa, 0x71, 0x22, 0xc4, 0x8d, 0x6d, 0xb4, 0xea, 0x32, 0x41,
	0x0d, 0x27, 0xfa, 0xb7, 0x5a, 0x3c, 0x1a, 0x6d, 0xab, 0xd7, 0xf5, 0xfe, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xc2, 0xf0, 0x45, 0xf3, 0x18, 0x04, 0x00, 0x00,
}
